# Base Configuration
# 
# This file contains the default configuration for the HIPAA de-identification system.
# Environment-specific configurations extend this base configuration.

# Security settings
security:
  # Salt for hashing identifiers (should be overridden in environment configs)
  salt: "CHANGE_THIS_IN_ENVIRONMENT_CONFIG"
  
  # Number of days to shift dates for de-identification
  date_shift_days: 30

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Models configuration
models:
  # spaCy model to use for NER (now integrated into Presidio)
  spacy: "en_core_web_lg"
  
  # Hugging Face model to use for medical entity detection
  huggingface: "obi/deid_bert_i2b2"
  
  # Device to use for ML inference (-1 for CPU, 0+ for specific GPU)
  device: -1

# Detection settings
detect:
  # Enable/disable detection methods
  enable_rules: true
  enable_spacy: true
  enable_ml: true
  
  # Strategic identifier-to-stage mapping
  # Each identifier is assigned to the most appropriate detection stage
  presidio_identifiers:
    # Presidio is best for high-precision, pattern-based identifiers
    - "PHONE_NUMBER"       # 4. Phone numbers
    - "FAX_NUMBER"         # 5. Fax numbers
    - "EMAIL_ADDRESS"      # 6. Email addresses
    - "US_SSN"             # 11. Social Security numbers
    - "URL"                # 7. URLs
    - "IP_ADDRESS"         # 15. IP addresses
    - "LICENSE_NUMBER"     # 12. Certificate/license numbers
    - "VEHICLE_ID"         # 13. Vehicle identifiers
    - "DEVICE_ID"          # 14. Device identifiers
    - "HEALTH_PLAN_ID"     # 9. Health plan beneficiary numbers
    - "ACCOUNT_NUMBER"     # 10. Account numbers
    - "BIOMETRIC_ID"       # 16. Biometric identifiers
    - "PHOTO_ID"           # 17. Full-face photographs
  
  # spaCy module is now integrated into Presidio, so these are empty
  spacy_identifiers: []
  
  hf_identifiers:
    # HF model is ONLY for contextual entities from the I2B2 training data
    - "NAME"               # 1. Names (PATIENT, STAFF)
    - "LOCATION"           # 2. Geographic subdivisions (LOC)
    - "ORGANIZATION"       # Hospitals, clinics, etc. (HOSP, PATORG)
    - "DATE"               # 3. Dates (DATE)
    - "AGE_OVER_89"        # Ages over 89 (AGE)
    - "MRN"                # 8. Medical record numbers (ID)

# Detection thresholds for sequential pipeline
# Higher thresholds ensure quality entities are passed to next stage
detection_thresholds:
  presidio: 0.6            # Standard threshold for Presidio (rule-based)
  hf: 4.656e-06            # 99.5% recall threshold for obi/deid_bert_i2b2

# Normalization settings (Stage 0)
normalization:
  # Enable de-hyphenation of OCR line-wrap artifacts
  enable_dehyphenation: true
  
  # Preserve hard tokens (URLs, emails, filenames) during normalization
  preserve_hard_tokens: true

# Transformation settings
transform:
  # Default action for PHI categories not explicitly listed
  default_action: redact
  
  # Specific rules for each PHI category based on HIPAA Safe Harbor
  rules:
    NAME: pseudonym          # 1. Names - Replace with consistent pseudonym
    LOCATION: generalize     # 2. Geographic subdivisions - Generalize to higher level
    DATE: date_shift         # 3. Dates - Shift dates by a consistent amount
    PHONE_NUMBER: redact     # 4. Phone numbers - Completely redact
    FAX_NUMBER: redact       # 5. Fax numbers - Completely redact
    EMAIL_ADDRESS: redact    # 6. Email addresses - Completely redact
    US_SSN: redact           # 7. Social Security numbers - Completely redact
    MRN: hash                # 8. Medical record numbers - Replace with hash
    HEALTH_PLAN_ID: hash     # 9. Health plan beneficiary numbers - Replace with hash
    ACCOUNT_NUMBER: hash     # 10. Account numbers - Replace with hash
    LICENSE_NUMBER: hash     # 11. Certificate/license numbers - Replace with hash
    VEHICLE_ID: redact       # 12. Vehicle identifiers - Completely redact
    MEDICAL_DEVICE_ID: hash  # 13. Device identifiers - Replace with hash
    URL: redact              # 14. Web URLs - Completely redact
    IP_ADDRESS: redact       # 15. IP addresses - Completely redact
    BIOMETRIC_ID: redact     # 16. Biometric identifiers - Completely redact
    PHOTO_ID: redact         # 17. Full-face photographs - Completely redact
    OTHER_ID: redact         # 18. Any other unique identifying - Completely redact
    
    # Clinical information to preserve (prevent over-redaction)
    MEDICATION: preserve     # Medication names should be preserved
    MEDICAL_PROCEDURE: preserve  # Medical procedures should be preserved
    LAB_VALUE: preserve      # Laboratory values should be preserved
    SYMPTOM: preserve        # Symptoms should be preserved
    CONDITION: preserve      # Medical conditions should be preserved
    VITAL_SIGN: preserve     # Vital signs should be preserved

# Pseudonym and hash formatting
pseudonym_formats:
  DEFAULT: "{code}"
  NAME: "PERSON_{code}"
  MRN: "MRN_{code}"
  HEALTH_PLAN_ID: "HPID_{code}"
  ACCOUNT_NUMBER: "ACCT_{code}"
  LICENSE_NUMBER: "LIC_{code}"
  VEHICLE_ID: "VIN_{code}"
  DEVICE_ID: "DEV_{code}"
  BIOMETRIC_ID: "BIO_{code}"

# Format templates for hashed values
hash_formats:
  MRN: "MRN_{code}"
  ENCOUNTER_ID: "ENC_{code}"
  ACCOUNT_NUMBER: "ACC_{code}"
  HEALTH_PLAN_ID: "INS_{code}"
  LICENSE_NUMBER: "LIC_{code}"
  MEDICAL_DEVICE_ID: "DEV_{code}"
  DEFAULT: "{code}"

# Date shifting settings
date_shift:
  # Preserve day of week when shifting dates
  preserve_day_of_week: true
  
  # Preserve month when shifting dates
  preserve_month: false