# Production Environment Configuration
# 
# This configuration extends the base configuration with production-specific settings.
# It is used for production deployments.

# Security settings for production environment
security:
  # In production, the salt should be set via environment variable
  # This is a fallback value that should be overridden
  salt: "CHANGE_ME_IN_PRODUCTION"
  date_shift_days: 30

# Logging settings for production
logging:
  level: "WARNING"

# Models configuration for production
models:
  spacy: "en_core_web_lg"
  huggingface: "obi/deid_bert_i2b2"
  device: 0  # Use GPU if available in production

# Detection thresholds for sequential pipeline
# Higher thresholds ensure quality entities are passed to next stage
detection_thresholds:
  patterns: 0.7  # Threshold for pattern-based detection
  spacy: 0.9  # High threshold for spaCy to pass quality entities to HF
  huggingface: 0.9  # High threshold for HF to ensure only confident medical entities