# Testing Environment Configuration
# 
# This configuration extends the base configuration with testing-specific settings.
# It is used for automated tests and CI/CD pipelines.

# Security settings for testing environment
security:
  salt: "TEST_SALT_CONSISTENT_FOR_TESTS"
  date_shift_days: 30

# Logging settings for testing
logging:
  level: "ERROR"  # Minimal logging during tests

# Models configuration for testing
models:
  spacy: "en_core_web_lg"
  huggingface: "obi/deid_bert_i2b2"
  device: -1  # Use CPU for testing

# Detection thresholds for sequential pipeline
# Higher thresholds ensure quality entities are passed to next stage
detection_thresholds:
  patterns: 0.7  # Threshold for pattern-based detection
  spacy: 0.9  # High threshold for spaCy to pass quality entities to HF
  huggingface: 0.9  # High threshold for HF to ensure only confident medical entities